import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rockyCondensed = localFont({
  src: "../../public/rocky-condensed-light.otf",
  variable: "--font-rocky-condensed",
  display: "swap",
});

export const metadata: Metadata = {
  title: "MEC Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rockyCondensed.variable}>
      <body className={rockyCondensed.className}>{children}</body>
    </html>
  );
}
